import {
  normaliserParametresAlertes,
  PARAMETRES_ALERTES_DEFAUT,
} from "./alertes";
import { createDefaultModeles } from "./document-templates";
import { ficheTiersDiversMarche } from "./missions";
import { seedCategoriesProduits } from "./produits";
import { fusionnerUnitesMesure, seedUnitesMesure } from "./unites-mesure";
import { fusionnerTypesClients, seedTypesClients } from "./types-clients";
import type { AppState } from "./types";

/** État métier vide — plus de données fake côté client. */
export function emptyAppState(): AppState {
  return {
    pointDeVenteActifId: "tous",
    parametres: {
      nomEntreprise: "",
      formeJuridique: "SARL",
      capital: 0,
      devise: "Ar",
      nif: "",
      stat: "",
      rcs: "",
      adresse: "",
      ville: "",
      telephone: "",
      email: "",
      rib: "",
      banque: "",
      tauxTVA: 20,
      assujettiTVA: true,
      regimeFiscal: "tva",
      seuilMargePalier1Percent: 25,
      seuilMargePalier2Percent: 5,
      conditionsPaiementDefaut:
        "Paiement à 30 jours. Acompte de 30 % à la commande. Espèces, virement ou Mobile Money.",
      tranchesBalanceAgeeJours: [30, 60, 90],
    },
    identiteNavigation: { nom: "" },
    modelesDocuments: createDefaultModeles(),
    preferencesModeles: {},
    preferencesAffichage: {},
    parametresAlertes: { ...PARAMETRES_ALERTES_DEFAUT },
    alertesSuivi: {},
    bilanInitial: {
      date: new Date().toISOString(),
      immobilisations: 0,
      stocks: 0,
      creancesClients: 0,
      disponibilites: 0,
      capital: 0,
      dettesFournisseurs: 0,
      dettesSociales: 0,
      emprunts: 0,
      resultatReporte: 0,
      compteCourantAssocie: 0,
    },
    immobilisations: [],
    mouvementsCompteCourant: [],
    clients: [],
    fournisseurs: [],
    tiers: [ficheTiersDiversMarche()],
    devis: [],
    commandes: [],
    bonsDeLivraison: [],
    factures: [],
    acomptes: [],
    transformations: [],
    achats: [],
    transfertsStock: [],
    ordresFabrication: [],
    missionsAchat: [],
    demandesPrix: [],
    pointsDeVente: [],
    categoriesProduits: seedCategoriesProduits(),
    unitesMesure: seedUnitesMesure(),
    typesClients: seedTypesClients(),
    exercicesComptables: [],
    produits: [],
    tarifsClients: [],
    historiquesPrix: [],
    journalAudit: [],
    entrees: [],
    ventes: [],
    charges: [],
    rapportsFinJournee: [],
    inventaires: [],
    journalActivites: [],
    comptesComptables: [],
    ecrituresComptables: [],
    transfertsComptables: [],
  };
}

export function pickAppState(state: AppState): AppState {
  return {
    parametres: state.parametres,
    identiteNavigation: state.identiteNavigation ?? { nom: "" },
    modelesDocuments: state.modelesDocuments,
    preferencesModeles: state.preferencesModeles ?? {},
    preferencesAffichage: state.preferencesAffichage ?? {},
    parametresAlertes: normaliserParametresAlertes(state.parametresAlertes),
    alertesSuivi: state.alertesSuivi ?? {},
    bilanInitial: state.bilanInitial,
    immobilisations: state.immobilisations,
    mouvementsCompteCourant: state.mouvementsCompteCourant ?? [],
    clients: state.clients,
    fournisseurs: state.fournisseurs,
    tiers: state.tiers ?? [],
    devis: state.devis,
    commandes: state.commandes,
    bonsDeLivraison: state.bonsDeLivraison,
    factures: state.factures,
    acomptes: state.acomptes,
    transformations: state.transformations ?? [],
    achats: state.achats ?? [],
    transfertsStock: state.transfertsStock ?? [],
    ordresFabrication: state.ordresFabrication ?? [],
    missionsAchat: state.missionsAchat ?? [],
    demandesPrix: state.demandesPrix ?? [],
    pointsDeVente: state.pointsDeVente,
    categoriesProduits: Array.isArray(state.categoriesProduits)
      ? state.categoriesProduits
      : seedCategoriesProduits(),
    unitesMesure: fusionnerUnitesMesure(state.unitesMesure, state.produits ?? []),
    typesClients: fusionnerTypesClients(
      state.typesClients,
      state.clients ?? [],
      state.tiers ?? [],
    ),
    exercicesComptables: Array.isArray(state.exercicesComptables)
      ? state.exercicesComptables
      : [],
    produits: state.produits ?? [],
    tarifsClients: state.tarifsClients,
    historiquesPrix: state.historiquesPrix,
    journalAudit: state.journalAudit,
    entrees: state.entrees,
    ventes: state.ventes,
    charges: state.charges,
    rapportsFinJournee: state.rapportsFinJournee ?? [],
    inventaires: state.inventaires ?? [],
    journalActivites: state.journalActivites ?? [],
    comptesComptables: state.comptesComptables ?? [],
    ecrituresComptables: state.ecrituresComptables ?? [],
    transfertsComptables: state.transfertsComptables ?? [],
    pointDeVenteActifId: state.pointDeVenteActifId,
  };
}
