export type LignePlanComptable = { numero: string; libelle: string };

/**
 * Référentiel PCG 2005 embarqué (Steward) — classes 1 à 8.
 * Hors comptes de TVA 445x (création manuelle).
 * Numéros sources 3 chiffres ou plus, pour ne pas entrer en collision
 * avec les comptes de repli 600000 / 700000 après complément de zéros.
 */
export const PLAN_PCG_2005: LignePlanComptable[] = [
  // Classe 1 — Capitaux
  { numero: "101", libelle: "Capital" },
  { numero: "104", libelle: "Primes liées au capital social" },
  { numero: "105", libelle: "Écarts de réévaluation" },
  { numero: "106", libelle: "Réserves" },
  { numero: "108", libelle: "Compte de l'exploitant" },
  { numero: "109", libelle: "Actionnaires : capital souscrit non appelé" },
  { numero: "110", libelle: "Report à nouveau (solde créditeur)" },
  { numero: "119", libelle: "Report à nouveau (solde débiteur)" },
  { numero: "120", libelle: "Résultat de l'exercice (bénéfice)" },
  { numero: "129", libelle: "Résultat de l'exercice (perte)" },
  { numero: "131", libelle: "Subventions d'équipement" },
  { numero: "138", libelle: "Autres subventions d'investissement" },
  { numero: "151", libelle: "Provisions pour risques" },
  { numero: "155", libelle: "Provisions pour impôts" },
  { numero: "157", libelle: "Provisions pour charges à répartir" },
  { numero: "158", libelle: "Autres provisions pour charges" },
  { numero: "161", libelle: "Emprunts obligataires convertibles" },
  { numero: "163", libelle: "Autres emprunts obligataires" },
  { numero: "164", libelle: "Emprunts auprès des établissements de crédit" },
  { numero: "165", libelle: "Dépôts et cautionnements reçus" },
  { numero: "168", libelle: "Autres emprunts et dettes assimilées" },
  { numero: "171", libelle: "Dettes rattachées à des participations" },
  { numero: "178", libelle: "Autres dettes rattachées à des participations" },

  // Classe 2 — Immobilisations
  { numero: "201", libelle: "Frais d'établissement" },
  { numero: "203", libelle: "Frais de recherche et de développement" },
  { numero: "205", libelle: "Concessions, brevets, licences, marques" },
  { numero: "206", libelle: "Droit au bail" },
  { numero: "207", libelle: "Fonds commercial" },
  { numero: "208", libelle: "Autres immobilisations incorporelles" },
  { numero: "211", libelle: "Terrains" },
  { numero: "213", libelle: "Constructions" },
  { numero: "215", libelle: "Installations techniques, matériel et outillage" },
  { numero: "2182", libelle: "Matériel de transport" },
  { numero: "2183", libelle: "Matériel de bureau et matériel informatique" },
  { numero: "2184", libelle: "Mobilier" },
  { numero: "218", libelle: "Autres immobilisations corporelles" },
  { numero: "231", libelle: "Immobilisations corporelles en cours" },
  { numero: "237", libelle: "Avances et acomptes versés sur immobilisations" },
  { numero: "261", libelle: "Titres de participation" },
  { numero: "266", libelle: "Autres formes de participation" },
  { numero: "267", libelle: "Créances rattachées à des participations" },
  { numero: "271", libelle: "Titres immobilisés (droit de propriété)" },
  { numero: "272", libelle: "Titres immobilisés (droit de créance)" },
  { numero: "274", libelle: "Prêts" },
  { numero: "275", libelle: "Dépôts et cautionnements versés" },
  { numero: "276", libelle: "Autres créances immobilisées" },

  // Classe 3 — Stocks
  { numero: "311", libelle: "Matières premières" },
  { numero: "321", libelle: "Matières consommables" },
  { numero: "322", libelle: "Fournitures consommables" },
  { numero: "326", libelle: "Emballages" },
  { numero: "331", libelle: "Produits en cours" },
  { numero: "335", libelle: "Travaux en cours" },
  { numero: "341", libelle: "Études en cours" },
  { numero: "345", libelle: "Prestations de services en cours" },
  { numero: "351", libelle: "Produits intermédiaires" },
  { numero: "355", libelle: "Produits finis" },
  { numero: "358", libelle: "Produits résiduels" },
  { numero: "371", libelle: "Marchandises" },
  { numero: "391", libelle: "Dépréciations des matières premières" },
  { numero: "397", libelle: "Dépréciations des stocks de marchandises" },

  // Classe 4 — Tiers (hors 445x TVA)
  { numero: "401", libelle: "Fournisseurs" },
  { numero: "403", libelle: "Fournisseurs — Effets à payer" },
  { numero: "404", libelle: "Fournisseurs d'immobilisations" },
  { numero: "408", libelle: "Fournisseurs — Factures non parvenues" },
  { numero: "409", libelle: "Fournisseurs débiteurs" },
  { numero: "411", libelle: "Clients" },
  { numero: "413", libelle: "Clients — Effets à recevoir" },
  { numero: "416", libelle: "Clients douteux ou litigieux" },
  { numero: "418", libelle: "Clients — Produits non encore facturés" },
  { numero: "419", libelle: "Clients créditeurs" },
  { numero: "421", libelle: "Personnel — Rémunérations dues" },
  { numero: "422", libelle: "Comités d'entreprise et d'établissement" },
  { numero: "424", libelle: "Participation des salariés aux résultats" },
  { numero: "425", libelle: "Personnel — Avances et acomptes" },
  { numero: "427", libelle: "Personnel — Opposition sur salaires" },
  { numero: "428", libelle: "Personnel — Charges à payer et produits à recevoir" },
  { numero: "431", libelle: "Sécurité sociale" },
  { numero: "437", libelle: "Autres organismes sociaux" },
  { numero: "438", libelle: "Organismes sociaux — Charges à payer" },
  { numero: "441", libelle: "État — Subventions à recevoir" },
  { numero: "442", libelle: "État — Impôts et taxes recouvrables sur des tiers" },
  { numero: "444", libelle: "État — Impôts sur les bénéfices" },
  { numero: "447", libelle: "Autres impôts, taxes et versements assimilés" },
  { numero: "448", libelle: "État — Charges à payer et produits à recevoir" },
  { numero: "451", libelle: "Groupe" },
  { numero: "455", libelle: "Associés — Comptes courants" },
  { numero: "456", libelle: "Associés — Opérations sur le capital" },
  { numero: "457", libelle: "Associés — Dividendes à payer" },
  { numero: "458", libelle: "Associés — Opérations faites en commun" },
  { numero: "462", libelle: "Créances sur cessions d'immobilisations" },
  { numero: "464", libelle: "Dettes sur acquisitions de valeurs mobilières" },
  { numero: "465", libelle: "Créances sur cessions de valeurs mobilières" },
  { numero: "467", libelle: "Autres comptes débiteurs ou créditeurs" },
  { numero: "468", libelle: "Divers — Charges à payer et produits à recevoir" },
  { numero: "471", libelle: "Comptes d'attente" },
  { numero: "476", libelle: "Différences de conversion — Actif" },
  { numero: "477", libelle: "Différences de conversion — Passif" },
  { numero: "478", libelle: "Autres comptes transitoires" },
  { numero: "481", libelle: "Charges à répartir sur plusieurs exercices" },
  { numero: "486", libelle: "Charges constatées d'avance" },
  { numero: "487", libelle: "Produits constatés d'avance" },
  { numero: "491", libelle: "Dépréciations des comptes de clients" },

  // Classe 5 — Financiers
  { numero: "501", libelle: "Parts dans des entreprises liées" },
  { numero: "502", libelle: "Actions propres" },
  { numero: "503", libelle: "Actions" },
  { numero: "506", libelle: "Obligations" },
  { numero: "507", libelle: "Bons du Trésor et bons de caisse" },
  { numero: "508", libelle: "Autres valeurs mobilières et créances assimilées" },
  { numero: "511", libelle: "Valeurs à l'encaissement" },
  { numero: "512", libelle: "Banques" },
  { numero: "514", libelle: "Chèques postaux" },
  { numero: "515", libelle: "Caisses du Trésor et des établissements publics" },
  { numero: "516", libelle: "Sociétés de bourse" },
  { numero: "517", libelle: "Autres organismes financiers" },
  { numero: "518", libelle: "Intérêts courus" },
  { numero: "519", libelle: "Concours bancaires courants" },
  { numero: "530", libelle: "Caisse" },
  { numero: "531", libelle: "Caisse siège" },
  { numero: "532", libelle: "Caisse succursale" },
  { numero: "540", libelle: "Régies d'avances et accréditifs" },
  { numero: "580", libelle: "Virements internes" },
  { numero: "590", libelle: "Dépréciations des valeurs mobilières de placement" },

  // Classe 6 — Charges
  { numero: "601", libelle: "Achats stockés — Matières premières" },
  { numero: "602", libelle: "Achats stockés — Autres approvisionnements" },
  { numero: "604", libelle: "Achats d'études et prestations de services" },
  { numero: "605", libelle: "Achats de matériel, équipements et travaux" },
  { numero: "607", libelle: "Achats de marchandises" },
  { numero: "608", libelle: "Frais accessoires d'achat" },
  { numero: "609", libelle: "Rabais, remises et ristournes obtenus sur achats" },
  { numero: "6031", libelle: "Variation des stocks de matières premières" },
  { numero: "6032", libelle: "Variation des stocks des autres approvisionnements" },
  { numero: "6037", libelle: "Variation des stocks de marchandises" },
  { numero: "611", libelle: "Sous-traitance générale" },
  { numero: "612", libelle: "Redevances de crédit-bail" },
  { numero: "613", libelle: "Locations" },
  { numero: "614", libelle: "Charges locatives et de copropriété" },
  { numero: "615", libelle: "Entretien et réparations" },
  { numero: "616", libelle: "Primes d'assurances" },
  { numero: "617", libelle: "Études et recherches" },
  { numero: "618", libelle: "Divers" },
  { numero: "621", libelle: "Personnel extérieur à l'entreprise" },
  { numero: "622", libelle: "Rémunérations d'intermédiaires et honoraires" },
  { numero: "623", libelle: "Publicité, publications, relations publiques" },
  { numero: "624", libelle: "Transports de biens et transports collectifs du personnel" },
  { numero: "625", libelle: "Déplacements, missions et réceptions" },
  { numero: "626", libelle: "Frais postaux et de télécommunications" },
  { numero: "627", libelle: "Services bancaires et assimilés" },
  { numero: "628", libelle: "Divers" },
  { numero: "631", libelle: "Impôts, taxes et versements assimilés sur rémunérations" },
  { numero: "633", libelle: "Impôts, taxes et versements assimilés sur rémunérations (autres)" },
  { numero: "635", libelle: "Autres impôts, taxes et versements assimilés" },
  { numero: "641", libelle: "Rémunérations du personnel" },
  { numero: "644", libelle: "Rémunération du travail de l'exploitant" },
  { numero: "645", libelle: "Charges de sécurité sociale et de prévoyance" },
  { numero: "647", libelle: "Autres charges sociales" },
  { numero: "648", libelle: "Autres charges de personnel" },
  { numero: "651", libelle: "Redevances pour concessions, brevets, licences" },
  { numero: "653", libelle: "Jetons de présence" },
  { numero: "654", libelle: "Pertes sur créances irrécouvrables" },
  { numero: "655", libelle: "Quotes-parts de résultat sur opérations faites en commun" },
  { numero: "658", libelle: "Charges diverses de gestion courante" },
  { numero: "661", libelle: "Charges d'intérêts" },
  { numero: "664", libelle: "Pertes sur créances liées à des participations" },
  { numero: "665", libelle: "Escomptes accordés" },
  { numero: "666", libelle: "Pertes de change" },
  { numero: "667", libelle: "Charges nettes sur cessions de VMP" },
  { numero: "668", libelle: "Autres charges financières" },
  { numero: "671", libelle: "Charges exceptionnelles sur opérations de gestion" },
  { numero: "672", libelle: "Charges sur exercices antérieurs" },
  { numero: "675", libelle: "Valeurs comptables des éléments d'actif cédés" },
  { numero: "678", libelle: "Autres charges exceptionnelles" },
  { numero: "681", libelle: "Dotations aux amortissements et provisions — exploitation" },
  { numero: "686", libelle: "Dotations aux amortissements et provisions — financier" },
  { numero: "687", libelle: "Dotations aux amortissements et provisions — exceptionnel" },
  { numero: "691", libelle: "Participation des salariés aux résultats" },
  { numero: "695", libelle: "Impôts sur les bénéfices" },
  { numero: "698", libelle: "Intégration fiscale — Charges" },
  { numero: "699", libelle: "Produits — Reports en arrière des déficits" },

  // Classe 7 — Produits
  { numero: "701", libelle: "Ventes de produits finis" },
  { numero: "702", libelle: "Ventes de produits intermédiaires" },
  { numero: "703", libelle: "Ventes de produits résiduels" },
  { numero: "704", libelle: "Travaux" },
  { numero: "705", libelle: "Études" },
  { numero: "706", libelle: "Prestations de services" },
  { numero: "707", libelle: "Ventes de marchandises" },
  { numero: "708", libelle: "Produits des activités annexes" },
  { numero: "709", libelle: "Rabais, remises et ristournes accordés par l'entreprise" },
  { numero: "713", libelle: "Variation des stocks (en-cours, produits)" },
  { numero: "721", libelle: "Production immobilisée — Immobilisations incorporelles" },
  { numero: "722", libelle: "Production immobilisée — Immobilisations corporelles" },
  { numero: "740", libelle: "Subventions d'exploitation" },
  { numero: "751", libelle: "Redevances pour concessions, brevets, licences" },
  { numero: "752", libelle: "Revenus des immeubles non affectés à des activités" },
  { numero: "753", libelle: "Jetons de présence et rémunérations d'administrateurs" },
  { numero: "754", libelle: "Ristournes perçues des coopératives" },
  { numero: "755", libelle: "Quotes-parts de résultat sur opérations faites en commun" },
  { numero: "756", libelle: "Gains de change sur créances commerciales" },
  { numero: "758", libelle: "Produits divers de gestion courante" },
  { numero: "761", libelle: "Produits de participations" },
  { numero: "762", libelle: "Produits des autres immobilisations financières" },
  { numero: "763", libelle: "Revenus des autres créances" },
  { numero: "764", libelle: "Revenus des valeurs mobilières de placement" },
  { numero: "765", libelle: "Escomptes obtenus" },
  { numero: "766", libelle: "Gains de change" },
  { numero: "767", libelle: "Produits nets sur cessions de VMP" },
  { numero: "768", libelle: "Autres produits financiers" },
  { numero: "771", libelle: "Produits exceptionnels sur opérations de gestion" },
  { numero: "772", libelle: "Produits sur exercices antérieurs" },
  { numero: "775", libelle: "Produits des cessions d'éléments d'actif" },
  { numero: "777", libelle: "Quote-part des subventions d'investissement virée au résultat" },
  { numero: "778", libelle: "Autres produits exceptionnels" },
  { numero: "781", libelle: "Reprises sur amortissements et provisions — exploitation" },
  { numero: "786", libelle: "Reprises sur provisions — financier" },
  { numero: "787", libelle: "Reprises sur provisions — exceptionnel" },
  { numero: "791", libelle: "Transferts de charges d'exploitation" },
  { numero: "796", libelle: "Transferts de charges financières" },
  { numero: "797", libelle: "Transferts de charges exceptionnelles" },

  // Classe 8 — Comptes spéciaux
  { numero: "801", libelle: "Engagements donnés par l'entité" },
  { numero: "802", libelle: "Engagements reçus par l'entité" },
  { numero: "809", libelle: "Contrepartie des engagements" },
];
