import { createDefaultModeles } from "./document-templates";
import type { AppState } from "./types";

const today = new Date();
const iso = (daysAgo: number, hour = 10) => {
  const d = new Date(today);
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const seedData: AppState = {
  pointDeVenteActifId: "tous",
  parametres: {
    nomEntreprise: "STWR Poissonnerie",
    formeJuridique: "SARL",
    capital: 225_000_000,
    devise: "Ar",
    nif: "5000123456",
    stat: "60101 11 2020 0 12345",
    rcs: "Antananarivo B 2020 000123",
    adresse: "Marché Analakely",
    ville: "Antananarivo",
    telephone: "034 00 111 22",
    email: "contact@stwr-poissonnerie.mg",
    rib: "00001 00002 12345678901 23",
    banque: "BFV-SG Madagascar",
    tauxTVA: 20,
    assujettiTVA: true,
    regimeFiscal: "tva",
    seuilMargePalier1Percent: 25,
    seuilMargePalier2Percent: 5,
    conditionsPaiementDefaut:
      "Paiement à 30 jours. Acompte de 30 % à la commande. Espèces, virement ou Mobile Money.",
  },
  modelesDocuments: createDefaultModeles(),
  bilanInitial: {
    date: iso(120),
    immobilisations: 85_000_000,
    stocks: 12_000_000,
    creancesClients: 3_500_000,
    disponibilites: 45_000_000,
    capital: 225_000_000,
    dettesFournisseurs: 8_000_000,
    dettesSociales: 2_500_000,
    emprunts: 15_000_000,
    resultatReporte: 5_000_000,
  },
  immobilisations: [
    {
      id: "immo-1",
      libelle: "Chambre froide positive",
      categorie: "materiel_froid",
      dateAcquisition: iso(400),
      valeurAcquisition: 45_000_000,
      dureeAmortissementAns: 10,
      pointDeVenteId: "pdv-marche",
    },
    {
      id: "immo-2",
      libelle: "Vitrine réfrigérée",
      categorie: "materiel_froid",
      dateAcquisition: iso(200),
      valeurAcquisition: 18_000_000,
      dureeAmortissementAns: 7,
      pointDeVenteId: "pdv-centre",
    },
    {
      id: "immo-3",
      libelle: "Camionnette utilitaire",
      categorie: "vehicule",
      dateAcquisition: iso(90),
      valeurAcquisition: 35_000_000,
      dureeAmortissementAns: 5,
      pointDeVenteId: "tous",
    },
    {
      id: "immo-4",
      libelle: "Balance électronique",
      categorie: "materiel",
      dateAcquisition: iso(30),
      valeurAcquisition: 2_800_000,
      dureeAmortissementAns: 5,
      pointDeVenteId: "pdv-port",
    },
  ],
  clients: [
    {
      id: "cli-1",
      nom: "Restaurant La Mer",
      telephone: "034 11 222 33",
      email: "contact@lamer.mg",
      adresse: "Rue Ratsimilaho",
      ville: "Antananarivo",
      nif: "4000987654",
      type: "restaurant",
      actif: true,
    },
    {
      id: "cli-2",
      nom: "Hôtel Colbert",
      telephone: "020 22 202 02",
      adresse: "Rue Passamanty",
      ville: "Antananarivo",
      nif: "4000555123",
      type: "hotel",
      actif: true,
    },
    {
      id: "cli-3",
      nom: "Grossiste Poissons Est",
      telephone: "034 55 666 77",
      ville: "Toamasina",
      type: "grossiste",
      actif: true,
    },
  ],
  fournisseurs: [
    {
      id: "frn-1",
      nom: "Mareyeurs Toamasina",
      telephone: "034 10 200 30",
      ville: "Toamasina",
      specialite: "Poissons de mer",
      actif: true,
    },
    {
      id: "frn-2",
      nom: "Pêcheurs Mahajanga",
      telephone: "034 40 500 60",
      ville: "Mahajanga",
      specialite: "Crustacés",
      actif: true,
    },
    {
      id: "frn-3",
      nom: "Coquillages Fort-Dauphin",
      telephone: "034 70 800 90",
      ville: "Fort-Dauphin",
      specialite: "Coquillages",
      actif: true,
    },
  ],
  devis: [
    {
      id: "dev-1",
      numero: "DEV-2026-0001",
      clientId: "cli-1",
      pointDeVenteId: "pdv-marche",
      date: iso(3),
      validiteJours: 15,
      statut: "accepte",
      tauxTVA: 20,
      conditionsPaiement:
        "Acompte 30 % à la commande, solde à la livraison.",
      lignes: [
        {
          id: "dl-1",
          produitId: "prod-saumon",
          designation: "Saumon Atlantique",
          quantite: 10,
          prixUnitaire: 110_000,
          unite: "kg",
        },
        {
          id: "dl-2",
          produitId: "prod-crevette",
          designation: "Crevettes roses",
          quantite: 5,
          prixUnitaire: 125_000,
          unite: "kg",
        },
      ],
    },
  ],
  commandes: [
    {
      id: "cmd-1",
      numero: "CMD-2026-0001",
      clientId: "cli-1",
      pointDeVenteId: "pdv-marche",
      date: iso(2),
      dateLivraisonPrevue: iso(-5),
      statut: "confirmee",
      devisId: "dev-1",
      tauxTVA: 20,
      conditionsPaiement:
        "Acompte 30 % à la commande, solde à la livraison.",
      lignes: [
        {
          id: "cl-1",
          produitId: "prod-saumon",
          designation: "Saumon Atlantique",
          quantite: 10,
          prixUnitaire: 110_000,
          unite: "kg",
        },
        {
          id: "cl-2",
          produitId: "prod-crevette",
          designation: "Crevettes roses",
          quantite: 5,
          prixUnitaire: 125_000,
          unite: "kg",
        },
      ],
    },
  ],
  bonsDeLivraison: [
    {
      id: "bl-1",
      numero: "BL-2026-0001",
      clientId: "cli-1",
      pointDeVenteId: "pdv-marche",
      date: iso(1),
      dateLivraison: iso(1),
      statut: "prepare",
      commandeId: "cmd-1",
      devisId: "dev-1",
      tauxTVA: 20,
      conditionsPaiement:
        "Acompte 30 % à la commande, solde à la livraison.",
      lignes: [
        {
          id: "bl-l-1",
          produitId: "prod-saumon",
          designation: "Saumon Atlantique",
          quantite: 10,
          prixUnitaire: 110_000,
          unite: "kg",
        },
        {
          id: "bl-l-2",
          produitId: "prod-crevette",
          designation: "Crevettes roses",
          quantite: 5,
          prixUnitaire: 125_000,
          unite: "kg",
        },
      ],
    },
  ],
  factures: [
    {
      id: "fac-aco-1",
      numero: "FAC-ACO-2026-0001",
      type: "acompte",
      clientId: "cli-1",
      pointDeVenteId: "pdv-marche",
      date: iso(2),
      echeance: iso(2),
      statut: "payee",
      montantPaye: 621_000,
      commandeId: "cmd-1",
      devisId: "dev-1",
      tauxTVA: 20,
      note: "Facture d'acompte 30 % — législation MG",
      acomptesDocument: [],
      lignes: [
        {
          id: "fa-1",
          designation: "Acompte 30 % sur commande CMD-2026-0001",
          quantite: 1,
          prixUnitaire: 517_500,
          unite: "forfait",
        },
      ],
    },
    {
      id: "fac-1",
      numero: "FAC-2026-0001",
      type: "standard",
      clientId: "cli-2",
      pointDeVenteId: "pdv-centre",
      date: iso(5),
      echeance: iso(-10),
      statut: "partiellement_payee",
      montantPaye: 1_000_000,
      tauxTVA: 20,
      acomptesDocument: [],
      lignes: [
        {
          id: "fl-1",
          produitId: "prod-bar",
          codeProduit: "BAR-LIGNE",
          designation: "BAR-LIGNE — Bar de ligne frais",
          quantite: 8,
          prixUnitaire: 155_000,
          unite: "kg",
          tauxTVA: 20,
        },
        {
          id: "fl-2",
          produitId: "prod-homard",
          codeProduit: "HOMARD",
          designation: "HOMARD — Homard vivant",
          quantite: 3,
          prixUnitaire: 305_000,
          unite: "kg",
          tauxTVA: 20,
        },
      ],
    },
    {
      id: "fac-2",
      numero: "FAC-2026-0002",
      type: "standard",
      clientId: "cli-3",
      pointDeVenteId: "pdv-port",
      date: iso(1),
      echeance: iso(-14),
      statut: "validee",
      montantPaye: 0,
      tauxTVA: 20,
      acomptesDocument: [],
      lignes: [
        {
          id: "fl-3",
          produitId: "prod-cabillaud",
          codeProduit: "CABILLAUD",
          designation: "CABILLAUD — Cabillaud frais",
          quantite: 25,
          prixUnitaire: 88_000,
          unite: "kg",
          tauxTVA: 20,
        },
      ],
    },
  ],
  acomptes: [
    {
      id: "aco-1",
      numero: "ACO-2026-0001",
      date: iso(2),
      clientId: "cli-1",
      montantTTC: 621_000,
      tauxTVA: 20,
      modePaiement: "virement",
      devisId: "dev-1",
      commandeId: "cmd-1",
      factureAcompteId: "fac-aco-1",
      factureId: "fac-aco-1",
      statut: "impute",
      note: "Acompte 30 % commande CMD-2026-0001",
    },
  ],
  pointsDeVente: [
    {
      id: "pdv-marche",
      nom: "Poissonnerie Analakely",
      adresse: "Marché Analakely",
      ville: "Antananarivo",
      telephone: "034 00 111 22",
      actif: true,
      objectifCAMensuel: 25_000_000,
    },
    {
      id: "pdv-port",
      nom: "Étal Port Toamasina",
      adresse: "Quai du Port",
      ville: "Toamasina",
      telephone: "034 00 333 44",
      actif: true,
      objectifCAMensuel: 18_000_000,
    },
    {
      id: "pdv-centre",
      nom: "Boutique Mahamasina",
      adresse: "45 rue Rainandriamampandry",
      ville: "Antananarivo",
      telephone: "034 00 666 77",
      actif: true,
      objectifCAMensuel: 22_000_000,
    },
  ],
  produits: [
    {
      id: "prod-saumon",
      code: "SAUMON-ATL",
      libelleCourt: "Saumon Atlantique",
      libelleLong: "Saumon Atlantique frais",
      categorieId: "cat-poisson",
      unite: "kg",
      prixAchat: 56_000,
      prixVenteHT: 112_000,
      prixVenteGrosHT: 98_000,
      seuilGros: 10,
      tauxTVA: 20,
      actif: true,
    },
    {
      id: "prod-cabillaud",
      code: "CABILLAUD",
      libelleCourt: "Cabillaud",
      libelleLong: "Cabillaud frais",
      categorieId: "cat-poisson",
      unite: "kg",
      prixAchat: 44_000,
      prixVenteHT: 90_000,
      prixVenteGrosHT: 80_000,
      seuilGros: 10,
      tauxTVA: 20,
      actif: true,
    },
    {
      id: "prod-bar",
      code: "BAR-LIGNE",
      libelleCourt: "Bar de ligne",
      libelleLong: "Bar de ligne frais",
      categorieId: "cat-poisson",
      unite: "kg",
      prixAchat: 81_000,
      prixVenteHT: 157_000,
      tauxTVA: 20,
      actif: true,
    },
    {
      id: "prod-sole",
      code: "SOLE",
      libelleCourt: "Sole",
      libelleLong: "Sole fraîche",
      categorieId: "cat-poisson",
      unite: "kg",
      prixAchat: 99_000,
      prixVenteHT: 189_000,
      tauxTVA: 20,
      actif: true,
    },
    {
      id: "prod-crevette",
      code: "CREV-ROSE",
      libelleCourt: "Crevettes roses",
      libelleLong: "Crevettes roses décortiquées",
      categorieId: "cat-crustace",
      unite: "kg",
      prixAchat: 63_000,
      prixVenteHT: 128_000,
      prixVenteGrosHT: 115_000,
      seuilGros: 5,
      tauxTVA: 20,
      actif: true,
    },
    {
      id: "prod-homard",
      code: "HOMARD",
      libelleCourt: "Homard vivant",
      libelleLong: "Homard vivant",
      categorieId: "cat-crustace",
      unite: "kg",
      prixAchat: 158_000,
      prixVenteHT: 310_000,
      tauxTVA: 20,
      actif: true,
    },
    {
      id: "prod-huitre",
      code: "HUITRE-N3",
      libelleCourt: "Huîtres n°3",
      libelleLong: "Huîtres n°3",
      categorieId: "cat-coquillage",
      unite: "piece",
      prixAchat: 2_000,
      prixVenteHT: 5_400,
      tauxTVA: 20,
      actif: true,
    },
    {
      id: "prod-moule",
      code: "MOULE-BOUCHOT",
      libelleCourt: "Moules de bouchot",
      libelleLong: "Moules de bouchot",
      categorieId: "cat-coquillage",
      unite: "kg",
      prixAchat: 14_000,
      prixVenteHT: 31_000,
      tauxTVA: 20,
      actif: true,
    },
  ],
  categoriesProduits: [
    {
      id: "cat-mer",
      code: "MER",
      libelle: "Produits de la mer",
      ordre: 1,
      actif: true,
    },
    {
      id: "cat-poisson",
      code: "POISSON",
      libelle: "Poissons",
      parentId: "cat-mer",
      ordre: 1,
      actif: true,
    },
    {
      id: "cat-crustace",
      code: "CRUSTACE",
      libelle: "Crustacés",
      parentId: "cat-mer",
      ordre: 2,
      actif: true,
    },
    {
      id: "cat-coquillage",
      code: "COQUILLAGE",
      libelle: "Coquillages",
      parentId: "cat-mer",
      ordre: 3,
      actif: true,
    },
    {
      id: "cat-autre",
      code: "AUTRE",
      libelle: "Autre",
      ordre: 99,
      actif: true,
    },
  ],
  tarifsClients: [
    {
      id: "tarif-1",
      clientId: "cli-1",
      produitId: "prod-saumon",
      prixHT: 105_000,
      typeTarif: "fixe",
      actif: true,
    },
  ],
  historiquesPrix: [],
  journalAudit: [],
  entrees: [
    {
      id: "ent-si-1",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-saumon",
      quantite: 20,
      prixAchatUnitaire: 52_000,
      prixVenteUnitaire: 105_000,
      fournisseur: "Stock initial",
      date: `${new Date().getFullYear()}-01-01T08:00:00.000Z`,
      note: "Ouverture d'inventaire",
      origine: "stock_initial" as const,
    },
    {
      id: "ent-si-2",
      pointDeVenteId: "pdv-port",
      produitId: "prod-crevette",
      quantite: 15,
      prixAchatUnitaire: 58_000,
      prixVenteUnitaire: 120_000,
      fournisseur: "Stock initial",
      date: `${new Date().getFullYear()}-01-01T08:00:00.000Z`,
      note: "Ouverture d'inventaire",
      origine: "stock_initial" as const,
    },
    {
      id: "ent-1",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-saumon",
      quantite: 45,
      prixAchatUnitaire: 55_000,
      prixVenteUnitaire: 110_000,
      fournisseur: "Mareyeurs Toamasina",
      date: iso(2, 6),
    },
    {
      id: "ent-2",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-cabillaud",
      quantite: 60,
      prixAchatUnitaire: 43_000,
      prixVenteUnitaire: 88_000,
      fournisseur: "Mareyeurs Toamasina",
      date: iso(2, 6),
    },
    {
      id: "ent-3",
      pointDeVenteId: "pdv-port",
      produitId: "prod-bar",
      quantite: 25,
      prixAchatUnitaire: 80_000,
      prixVenteUnitaire: 155_000,
      fournisseur: "Pêcheurs Mahajanga",
      date: iso(1, 7),
    },
    {
      id: "ent-4",
      pointDeVenteId: "pdv-port",
      produitId: "prod-crevette",
      quantite: 30,
      prixAchatUnitaire: 61_000,
      prixVenteUnitaire: 125_000,
      fournisseur: "Aquaculture Ouest",
      date: iso(1, 7),
    },
    {
      id: "ent-5",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-huitre",
      quantite: 400,
      prixAchatUnitaire: 1_900,
      prixVenteUnitaire: 5_200,
      fournisseur: "Coquillages Fort-Dauphin",
      date: iso(3, 8),
    },
    {
      id: "ent-6",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-moule",
      quantite: 80,
      prixAchatUnitaire: 14_000,
      prixVenteUnitaire: 30_000,
      fournisseur: "Coquillages Fort-Dauphin",
      date: iso(3, 8),
    },
    {
      id: "ent-7",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-sole",
      quantite: 18,
      prixAchatUnitaire: 97_000,
      prixVenteUnitaire: 185_000,
      fournisseur: "Mareyeurs Toamasina",
      date: iso(5, 6),
    },
    {
      id: "ent-8",
      pointDeVenteId: "pdv-port",
      produitId: "prod-homard",
      quantite: 12,
      prixAchatUnitaire: 153_000,
      prixVenteUnitaire: 305_000,
      fournisseur: "Pêcheurs Mahajanga",
      date: iso(4, 7),
    },
    {
      id: "ent-9",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-saumon",
      quantite: 40,
      prixAchatUnitaire: 58_000,
      prixVenteUnitaire: 115_000,
      fournisseur: "Mareyeurs Toamasina",
      date: iso(10, 6),
    },
    {
      id: "ent-10",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-cabillaud",
      quantite: 35,
      prixAchatUnitaire: 45_000,
      prixVenteUnitaire: 92_000,
      fournisseur: "Aquaculture Ouest",
      date: iso(12, 8),
    },
    {
      id: "ent-11",
      pointDeVenteId: "pdv-port",
      produitId: "prod-moule",
      quantite: 100,
      prixAchatUnitaire: 13_500,
      prixVenteUnitaire: 29_000,
      fournisseur: "Coquillages Fort-Dauphin",
      date: iso(20, 7),
    },
    {
      id: "ent-12",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-crevette",
      quantite: 25,
      prixAchatUnitaire: 64_000,
      prixVenteUnitaire: 130_000,
      fournisseur: "Aquaculture Ouest",
      date: iso(25, 6),
    },
  ],
  ventes: [
    {
      id: "v-1",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-saumon",
      quantite: 8.5,
      prixUnitaire: 110_000,
      date: iso(0, 11),
    },
    {
      id: "v-2",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-cabillaud",
      quantite: 12,
      prixUnitaire: 88_000,
      date: iso(0, 14),
    },
    {
      id: "v-3",
      pointDeVenteId: "pdv-port",
      produitId: "prod-bar",
      quantite: 4.2,
      prixUnitaire: 155_000,
      date: iso(0, 12),
    },
    {
      id: "v-4",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-huitre",
      quantite: 48,
      prixUnitaire: 5_200,
      date: iso(0, 13),
    },
    {
      id: "v-5",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-crevette",
      quantite: 6,
      prixUnitaire: 128_000,
      date: iso(1, 11),
    },
    {
      id: "v-6",
      pointDeVenteId: "pdv-port",
      produitId: "prod-homard",
      quantite: 2.5,
      prixUnitaire: 310_000,
      date: iso(1, 15),
    },
    {
      id: "v-7",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-moule",
      quantite: 22,
      prixUnitaire: 30_000,
      date: iso(1, 10),
    },
    {
      id: "v-8",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-sole",
      quantite: 3.8,
      prixUnitaire: 189_000,
      date: iso(2, 12),
    },
    {
      id: "v-9",
      pointDeVenteId: "pdv-port",
      produitId: "prod-saumon",
      quantite: 5,
      prixUnitaire: 112_000,
      date: iso(2, 14),
    },
    {
      id: "v-10",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-cabillaud",
      quantite: 7.5,
      prixUnitaire: 90_000,
      date: iso(3, 11),
    },
    {
      id: "v-11",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-bar",
      quantite: 3,
      prixUnitaire: 157_000,
      date: iso(4, 13),
    },
    {
      id: "v-12",
      pointDeVenteId: "pdv-port",
      produitId: "prod-crevette",
      quantite: 9,
      prixUnitaire: 125_000,
      date: iso(5, 12),
    },
    {
      id: "v-13",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-huitre",
      quantite: 72,
      prixUnitaire: 5_400,
      date: iso(6, 16),
    },
    {
      id: "v-14",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-saumon",
      quantite: 15,
      prixUnitaire: 112_000,
      date: iso(15, 11),
    },
    {
      id: "v-15",
      pointDeVenteId: "pdv-port",
      produitId: "prod-cabillaud",
      quantite: 18,
      prixUnitaire: 89_000,
      date: iso(18, 12),
    },
    {
      id: "v-16",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-moule",
      quantite: 40,
      prixUnitaire: 31_000,
      date: iso(22, 10),
    },
    {
      id: "v-17",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-crevette",
      quantite: 10,
      prixUnitaire: 128_000,
      date: iso(28, 14),
    },
    {
      id: "v-18",
      pointDeVenteId: "pdv-port",
      produitId: "prod-sole",
      quantite: 6,
      prixUnitaire: 185_000,
      date: iso(35, 11),
    },
    {
      id: "v-19",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-bar",
      quantite: 8,
      prixUnitaire: 157_000,
      date: iso(40, 13),
    },
    {
      id: "v-20",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-homard",
      quantite: 4,
      prixUnitaire: 305_000,
      date: iso(45, 15),
    },
    {
      id: "v-21",
      pointDeVenteId: "pdv-port",
      produitId: "prod-saumon",
      quantite: 20,
      prixUnitaire: 108_000,
      date: iso(60, 11),
    },
    {
      id: "v-22",
      pointDeVenteId: "pdv-centre",
      produitId: "prod-cabillaud",
      quantite: 25,
      prixUnitaire: 85_000,
      date: iso(70, 12),
    },
    {
      id: "v-23",
      pointDeVenteId: "pdv-marche",
      produitId: "prod-moule",
      quantite: 55,
      prixUnitaire: 29_000,
      date: iso(90, 10),
    },
    {
      id: "v-24",
      pointDeVenteId: "pdv-port",
      produitId: "prod-huitre",
      quantite: 120,
      prixUnitaire: 5_000,
      date: iso(100, 16),
    },
  ],
  charges: [
    {
      id: "ch-1",
      pointDeVenteId: "pdv-marche",
      libelle: "Loyer emplacement marché",
      montant: 8_100_000,
      categorie: "loyer",
      natureEconomique: "fixe_structure",
      date: iso(5),
      recurrent: true,
    },
    {
      id: "ch-2",
      pointDeVenteId: "pdv-port",
      libelle: "Loyer local portuaire",
      montant: 9_900_000,
      categorie: "loyer",
      natureEconomique: "fixe_structure",
      date: iso(5),
      recurrent: true,
    },
    {
      id: "ch-3",
      pointDeVenteId: "pdv-centre",
      libelle: "Loyer boutique",
      montant: 12_600_000,
      categorie: "loyer",
      natureEconomique: "fixe_structure",
      date: iso(5),
      recurrent: true,
    },
    {
      id: "ch-4",
      pointDeVenteId: "tous",
      libelle: "Salaires équipe",
      montant: 38_250_000,
      categorie: "salaires",
      natureEconomique: "fixe_structure",
      date: iso(3),
      recurrent: true,
    },
    {
      id: "ch-5",
      pointDeVenteId: "tous",
      libelle: "Charges sociales",
      montant: 14_400_000,
      categorie: "charges_sociales",
      natureEconomique: "fixe_structure",
      date: iso(3),
      recurrent: true,
    },
    {
      id: "ch-6",
      pointDeVenteId: "pdv-marche",
      libelle: "Électricité chambre froide",
      montant: 1_890_000,
      categorie: "energie",
      natureEconomique: "fixe_structure",
      date: iso(8),
      recurrent: true,
    },
    {
      id: "ch-7",
      pointDeVenteId: "pdv-port",
      libelle: "Électricité & glace",
      montant: 1_710_000,
      categorie: "energie",
      natureEconomique: "fixe_structure",
      date: iso(8),
      recurrent: true,
    },
    {
      id: "ch-8",
      pointDeVenteId: "tous",
      libelle: "Transport arrivages",
      montant: 2_925_000,
      categorie: "transport",
      natureEconomique: "variable_vente",
      date: iso(2),
      recurrent: false,
    },
    {
      id: "ch-9",
      pointDeVenteId: "pdv-centre",
      libelle: "Entretien vitrine",
      montant: 810_000,
      categorie: "entretien",
      natureEconomique: "fixe_structure",
      date: iso(12),
      recurrent: false,
    },
    {
      id: "ch-10",
      pointDeVenteId: "tous",
      libelle: "Achat emballages / sacs",
      montant: 1_200_000,
      categorie: "emballage",
      natureEconomique: "variable_vente",
      date: iso(4),
      recurrent: true,
    },
    {
      id: "ch-11",
      pointDeVenteId: "tous",
      libelle: "Téléphone & internet",
      montant: 450_000,
      categorie: "telephone",
      natureEconomique: "fixe_structure",
      date: iso(6),
      recurrent: true,
    },
    {
      id: "ch-12",
      pointDeVenteId: "pdv-marche",
      libelle: "Eau",
      montant: 180_000,
      categorie: "eau",
      natureEconomique: "fixe_structure",
      date: iso(7),
      recurrent: true,
    },
    {
      id: "ch-13",
      pointDeVenteId: "tous",
      libelle: "Frais divers / commissions",
      montant: 650_000,
      categorie: "frais",
      natureEconomique: "fixe_structure",
      date: iso(9),
      recurrent: false,
    },
    {
      id: "ch-14",
      pointDeVenteId: "tous",
      libelle: "Assurance locaux",
      montant: 2_100_000,
      categorie: "assurance",
      natureEconomique: "fixe_structure",
      date: iso(15),
      recurrent: true,
    },
  ],
};
